# Generated by Django 3.0.2 on 2022-04-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arts',
            options={'ordering': ['-changed_date', 'title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='arts',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='arts',
            name='changed_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='arts',
            name='creating_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='arts',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='arts',
            name='image',
            field=models.ImageField(blank=True, upload_to='arts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='arts',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='arts',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
    ]
